---

projects:
  - name: myproject
    registry:
      address: http://127.0.0.1:5000/
      credentials: ''
      repository: my/project
      rules:
        # default action
        - action: remove
        # save LIMIT newest "master.[0-9]+" tags
        - action: save
          regexp: '^master\.[0-9]+$'
          order: age
          limit: 10
        # save LIMIT newest across non-master tags
        - action: save
          regexp: '^(?!master).*$'
          order: age
          limit: 40

  - name: project-from-other-registry
    gitlab:
      secret_token: 'something'
    registry:
      address: https://registry.example.org
      credentials: 'admin:pass'
      repository: foo
      rules:
        # default action
        - action: save
        # remove images leaving LIMIT newest
        - action: remove
          order: age
          limit: 20
