---

projects:
  - name: myproject
    registry:
      address: http://127.0.0.1:5000/
      credentials: ''
    images:
      - repository: my/project
        rules:
          - action: remove
          # save LIMIT newest "master.[0-9]+" tags
          - action: save
            regexp: '^master\.[0-9]+$'
            order: created
            limit: 10
          # save LIMIT newest across non-master tags
          - action: save
            regexp: '^(?!master).*$'
            order: created
            limit: 40
          # save specific tag
          - action: save
            regexp: '^bar$'

  - name: group_name/another-project
    gitlab:
      secret_token: 'something'
    registry:
      address: https://registry.example.org
      verify_ssl: false
      credentials: 'admin:pass'
    images:
      - repository: foo
        rules:
          - action: save
          # remove images leaving LIMIT newest
          - action: remove
            order: created
            limit: 20
